//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QQlogin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QQlogin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 549000912 的本地化字符串。
        /// </summary>
        public static string aid {
            get {
                return ResourceManager.GetString("aid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fpsig=11004C4517696DB0E347016BBAF1B840538C482C598A587E4C42D67251B887C88693AD45BCBE166AE95DBCFB80360A93DA2D 的本地化字符串。
        /// </summary>
        public static string fpinfo {
            get {
                return ResourceManager.GetString("fpinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 if (typeof JSON !== &apos;object&apos;) {
        ///    JSON = {};
        ///}
        ///
        ///(function () {
        ///    &apos;use strict&apos;;
        ///
        ///    var rx_one = /^[\],:{}\s]*$/,
        ///        rx_two = /\\(?:[&quot;\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
        ///        rx_three = /&quot;[^&quot;\\\n\r]*&quot;|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
        ///        rx_four = /(?:^|:|,)(?:\s*\[)+/g,
        ///        rx_escapable = /[\\\&quot;\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
        ///        rx_dangerous = /[\u0000\u00ad\u060 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyA5XzEgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjAxLjEuNDYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzkuMCBNb2JpbGUvMTNCMTQzIFNhZmFyaS82MDEuMQ== 的本地化字符串。
        /// </summary>
        public static string ua {
            get {
                return ResourceManager.GetString("ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var window={};var navigator={};$=window.$||{},pt=window.pt||{},RSA=pt.RSA=function(){function t(t,e){return new r(t,e)}
        ///function e(t,e){if(e&lt;t.length+11)return uv_alert(&quot;Message too long for RSA&quot;),null;for(var i=new Array,n=t.length-1;n&gt;=0&amp;&amp;e&gt;0;){var o=t.charCodeAt(n--);i[--e]=o}
        ///i[--e]=0;for(var p=new Y,s=new Array;e&gt;2;){for(s[0]=0;0==s[0];)p.nextBytes(s);i[--e]=s[0]}
        ///return i[--e]=2,i[--e]=0,new r(i)}
        ///function i(){this.n=null,this.e=0,this.d=null,this.p=null,this.q=null,this.dmp1=null,this.dmq1=null,t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 密码加密JS {
            get {
                return ResourceManager.GetString("密码加密JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 user-agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 的本地化字符串。
        /// </summary>
        public static string 提交UA {
            get {
                return ResourceManager.GetString("提交UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var x = 0; 
        ///var blockSize = 4;
        ///var key = &apos;0123456789abcdef&apos;;
        ///var _map = &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=&quot;;
        ///var screenInfo = &apos;414-736-1040-24-*-*-*&apos;;
        ///var resolutionx = 414; 
        ///var resolutiony = 736; 
        ///var winSize = new Array(414, 736); 
        ///var ratio = 1.6;
        ///var ft = &apos;63_7Pfn7H&apos;;
        ///var jshook = 5;
        ///var os = &apos;IOS&apos;;
        ///var a = 774696253;
        ///var index = 0;
        ///var tokenid = 774696253;
        ///var tokents = 1515642445;
        ///var coordinate = new Array(0, 0, 0.6304);
        ///var elapsed = 1000;
        ///var mouse [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 轨迹加密js {
            get {
                return ResourceManager.GetString("轨迹加密js", resourceCulture);
            }
        }
    }
}
